In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
print(np.__version__)

2.5.0


In [4]:
# 1. Creating arrays
    # same kind of data are stored in an array

In [5]:
list1 = [1,2,3,4]
print(list1)
    # it prints in comma separated format

[1, 2, 3, 4]


In [6]:
arr_list1 = np.array(list1) # it is a one dimentional array
print(arr_list1)
    # it doesn't prints in comma separated format

print(type(arr_list1))

    # output
    # [1 2 3 4]
    # <class 'numpy.ndarray'>

[1 2 3 4]
<class 'numpy.ndarray'>


In [7]:
print(arr_list1.ndim)

1


In [8]:
list1 = [1,2,3,4,5,6]
list2 = [4,5,6,7,8,9]
arr_list1_2 = np.array([list1,list2])
print(arr_list1_2)

# Output
# Two dimentional array
# [[1 2 3 4 5 6]
#[4 5 6 7 8 9]]

[[1 2 3 4 5 6]
 [4 5 6 7 8 9]]


In [9]:
print(arr_list1_2.ndim)

2


In [10]:
list1 = [1,2,3,4,5,6]
list2 = [4,5,6,7,8,9]
list3 = [1,3,5,7,9,11]
arr_list1_3 = np.array([[list1,list2,list3]])
print(arr_list1_3)

print(arr_list1_3.ndim,"dimentional array")
# Output
# Three dimentional array
#[[ 1  2  3  4  5  6]
#[ 4  5  6  7  8  9]
#[ 1  3  5  7  9 11]]

[[[ 1  2  3  4  5  6]
  [ 4  5  6  7  8  9]
  [ 1  3  5  7  9 11]]]
3 dimentional array


In [11]:
print(arr_list1_3.ndim)

3


In [12]:
# 2. Numpy array attributes

In [13]:
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr1)

[[1 2 3 4]
 [5 6 7 8]]


In [14]:
print("Shape:",arr1.shape)# Shape of an array, row column 
print("Size:",arr1.size)# Size of an array, Counts the elements of an array
print("dType:",arr1.dtype) # DataType of an array (int, string, etc.)
print("n_dim:",arr1.ndim) # dimention of an array


Shape: (2, 4)
Size: 8
dType: int64
n_dim: 2


In [15]:
# Ex1. Create 2 array- 1D and 3D, and find it's attributes

In [16]:
array1 = np.array(["a","b","c"])
print(array1)
print(type(array1))
print("Shape:",array1.shape)
print("Size:", array1.size)
print("dType",array1.dtype)
print("N_dim:",array1.ndim)

['a' 'b' 'c']
<class 'numpy.ndarray'>
Shape: (3,)
Size: 3
dType <U1
N_dim: 1


In [17]:
array2 = np.array([[[1,2,3,4,5],[2,3,4,5,6],[1,2,3,4,5]]])
print("Shape:", array2.shape)
print("Size:", array2.size)
print("DType:", array2.dtype)
print("N_dim:",array2.ndim)

Shape: (1, 3, 5)
Size: 15
DType: int64
N_dim: 3


In [18]:
# 3. Array initialization methods

In [19]:
# Zero array method

zero_arr =  np.zeros((2,2))
print(zero_arr)

[[0. 0.]
 [0. 0.]]


In [20]:
# one array method

one_arr = np.ones((2,5))
print(one_arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [21]:
# full array method

full_arr =  np.full((3,4),5)
print(full_arr)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [22]:
full_arr = np.full((2,2),9)
print(full_arr)

[[9 9]
 [9 9]]


In [23]:
# Identity Matrix
    # NOTE: diagonal elements will be 1 and the remainings will be 0
id_arr = np.eye(4)
print(id_arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [24]:
# Empty array

print(np.empty(2))

[5.43230922e-312 7.29112202e-304]


In [25]:
# Evently spaced array
    # arange(start,stop,step)
print(np.arange(1,10,2))
    # Output
        # [1 3 5 7 9]

[1 3 5 7 9]


In [26]:
# Specific number of equally (spaced) values between a range

print(np.linspace(1,10,4))
    # output
        # [ 1.  4.  7. 10.]

[ 1.  4.  7. 10.]


In [27]:
# Random values array - float form

r_arr = np.random.rand(3,2)
print(r_arr)

[[0.51227822 0.73616988]
 [0.798077   0.17930087]
 [0.64054068 0.08303621]]


In [28]:
# Random values arry - int form
    # random value from 1-100
r_arr_int = np.random.randint(1,100,(3,4))
print(r_arr_int)

[[55 95 20 46]
 [31 33 59 98]
 [22 57 74 19]]


In [29]:
# Array indexing and slicing

In [30]:
# array[start:stop:step
# NOTE: stop-index is not included in the output

a = np.array([1,2,4,3,5,6,7])
print("Whole array is: ",a)
print("index value 2 is: ",a[2])
print("index value 2 to 4 is: ",a[1:4])
print("index value -2 is: ",a[-2])

print("slicing 2,3,6",a[1::2])
print("Slicing 1 3 7", a[::3])
print("Reverse", a[::-1])
print("First three element is:", a[:3])
print("Last three element is:", a[-3:])
 

Whole array is:  [1 2 4 3 5 6 7]
index value 2 is:  4
index value 2 to 4 is:  [2 4 3]
index value -2 is:  6
slicing 2,3,6 [2 3 6]
Slicing 1 3 7 [1 3 7]
Reverse [7 6 5 3 4 2 1]
First three element is: [1 2 4]
Last three element is: [5 6 7]


In [31]:
# Two dimentional array

arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)


[[1 2 3 4]
 [5 6 7 8]]


In [32]:
# indexing in two dimentional array
print("Two d array:\n",arr2)
print("Reverse:\n",arr2[::-1])
print("first row:\n",arr2[0])
print("last row:\n",arr2[1])
print("first row - third element:\n",arr2[0][2])
print("first row - first element:\n",arr2[0][0])
print("second row - first element:\n",arr2[1][0])
print("second row - first element:\n",arr2[1][0])

# Slicing in two d matrix

print("Slicing second row, 6 7 8 :",arr2[1][1:])
print("Slicing second row,5 6:",arr2[1][:2])

# slicing the row
print("Slicing:", arr2[:,3])

# Slicing [rows,cols]
print("Slicing",arr2[1:,3])


Two d array:
 [[1 2 3 4]
 [5 6 7 8]]
Reverse:
 [[5 6 7 8]
 [1 2 3 4]]
first row:
 [1 2 3 4]
last row:
 [5 6 7 8]
first row - third element:
 3
first row - first element:
 1
second row - first element:
 5
second row - first element:
 5
Slicing second row, 6 7 8 : [6 7 8]
Slicing second row,5 6: [5 6]
Slicing: [4 8]
Slicing [8]


In [33]:
arr3 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(arr3)
print(type(arr3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [34]:
print(arr3[0])
print(arr3[1])
print(arr3[2])

[1 2 3]
[4 5 6]
[7 8 9]


In [35]:
print(arr3[0][2]) # first row third element
print(arr3[0][0]) # first row first element

3
1


In [36]:
print(arr3[1][1]) # second row second element

5


In [37]:
print(arr3[2][2]) # third row,third element

9


In [38]:
print(arr3[0][1:]) # first row, second to all element

[2 3]


In [39]:
print(arr3[:,2]) # 3rd columns value

[3 6 9]


In [40]:
print(arr3[:,0]) # 1st col

[1 4 7]


In [41]:
# Syntax
# print(array[rows,cols])
print(arr3[::2,0])

[1 7]


In [42]:
print(arr3[1::,1:2])

[[5]
 [8]]


In [43]:
# 5. Array reshaping and flattening

In [44]:
arr1 = np.array([1,2,3,4,5,6])
print(arr1)

[1 2 3 4 5 6]


In [45]:
reshaped = arr1.reshape((6,1))
print(reshaped)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [46]:
print(arr1)

[1 2 3 4 5 6]


In [47]:
reshaped2 = arr1.reshape((2,3))
print(reshaped2)

[[1 2 3]
 [4 5 6]]


In [48]:
# Flattned
print(reshaped2.flatten())

[1 2 3 4 5 6]


In [49]:
# 6. Array stacking and splitting

In [54]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

print("This is verticle stack\n",np.vstack((a,b))) # Verticle stacking - row wise

print("This is horizontal stack:\n",np.hstack((a,b))) # Horizontal stacking - cols wise

This is verticle stack
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
This is horizontal stack:
 [ 1  2  3  4  5  6  7  8  9 10]


In [55]:
c = np.array([[1,2,3,4],[5,6,7,8]])
print(c)

[[1 2 3 4]
 [5 6 7 8]]


In [57]:
print(np.vstack(c))

[[1 2 3 4]
 [5 6 7 8]]


In [58]:
print(np.hstack(c))

[1 2 3 4 5 6 7 8]


In [60]:
print(np.hsplit(c,4))

[array([[1],
       [5]]), array([[2],
       [6]]), array([[3],
       [7]]), array([[4],
       [8]])]


In [61]:
split = np.hsplit(c,4) # horizontal split
for s in split:
    print(s)

[[1]
 [5]]
[[2]
 [6]]
[[3]
 [7]]
[[4]
 [8]]


In [64]:
vsplit = np.vsplit(c,2) # verticle split
for v in vsplit:
    print(v)

[[1 2 3 4]]
[[5 6 7 8]]


In [ ]:
# 7 Mathematical Operations on Array

In [67]:
a = np.array([1,2,-3,4,-15])
print(a)

[  1   2  -3   4 -15]


In [70]:
print(a + 10)
print(a - 30)
print(a * 4)
print(a / 3)

[11 12  7 14 -5]
[-29 -28 -33 -26 -45]
[  4   8 -12  16 -60]
[ 0.33333333  0.66666667 -1.          1.33333333 -5.        ]


In [71]:
b = np.array([1,4,9])
print(b)

[1 4 9]


In [73]:
print(np.sqrt(b))
print(np.square(b))

[1. 2. 3.]
[ 1 16 81]


In [74]:
# sin, tan, cos

In [75]:
print(np.sin(b))

[ 0.84147098 -0.7568025   0.41211849]


In [76]:
print(np.cos(b))

[ 0.54030231 -0.65364362 -0.91113026]


In [77]:
print(np.tan(b))

[ 1.55740772  1.15782128 -0.45231566]


In [81]:
# Mathematiclal Operations on Multiple Array

In [118]:
ma = np.array([1,3,4,5,16])
mb = np.array([5,6,3,8,10])


print("ma:\n",ma)
print("mb:\n",mb)
print("ma * mb:\n",ma * mb)
print("ma + mb:\n",ma + mb)
print("Addition:\n",np.add(ma,mb)) # 
print("Subtraction:\n",np.subtract(ma,mb))
print("Multiplication:\n",np.multiply(ma,mb))
print("Division:\n",np.divide(mb,ma))
print("ma Divide by 3:\n",np.divide(ma,3))
print("ma divide by 2:\n",np.multiply(ma,2))

ma:
 [1 2 3]
mb:
 [4 5 6]
ma * mb:
 [ 4 10 18]
ma + mb:
 [5 7 9]
Addition:
 [5 7 9]
Subtraction:
 [-3 -3 -3]
Multiplication:
 [ 4 10 18]
Division:
 [4.  2.5 2. ]
ma Divide by 3:
 [0.33333333 0.66666667 1.        ]
ma divide by 2:
 [2 4 6]


In [121]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.dot(a,b)) # dot product 
# 1 * 4, 2 * 5, 3 * 6
# 4 + 10 + 18

32


In [124]:
# Transpose

print(a.T)

[1 2 3]


In [127]:
t =  np.array([[1,2,3],
               [4,5,6]])
print(t)
print()
print(t.T) # transpose the position of an array from row to col 

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]


In [128]:
# 9. Statistical function

In [149]:
sa = np.array([[1,2,3,4],[5,6,7,8]])
print(sa)

[[1 2 3 4]
 [5 6 7 8]]


In [150]:
print(f"Sum: {np.sum(sa)}") # sum function

Sum: 36


In [151]:
print(f"Mean: {np.mean(sa)}") # mean 

Mean: 4.5


In [152]:
print(f" Median: {np.median(sa)}") # meddian

 Median: 4.5


In [153]:
print(f"Standard deviation: {np.std(sa)}") # Standard deviation

Standard deviation: 2.29128784747792


In [154]:
print(f"Minimum value: {np.min(sa)}")

Minimum value: 1


In [155]:
print(f"Maximum value: {np.max(sa)}")

Maximum value: 8


In [ ]:
# 10. Array comparision

In [163]:
a = np.array([1,2,3,4,5])
b = np.array([6,2,8,4,10])
print(a)
print(b)


[1 2 3 4 5]
[ 6  2  8  4 10]


In [164]:
print(a == b)  # comparing each element

[False  True False  True False]


In [165]:
print(np.array_equal(a,b)) # comparing complete array

False


In [166]:
# 11. Broadcasting
    # Broadcasting is a mechanism that allows arithmetic operations
    # to be performed on arrays of different shapes and sizes, 
    # it eliminates the need for explicit loops or 
    # reshaping operations, 
    # making code more concise, 
    # readable and efficient.

In [169]:
a = np.array([1,2,3,4,5])
b = np.array([5])
# one dimentional array
print(a + b)

[ 6  7  8  9 10]


In [174]:
c = np.array([[1,2,3],[4,5,6]])
d = np.array([10,11,12])
# two dimentional array
print("Addition:\n",c + d)
print("Subtraction:\n",c - d)
print("Multiplication:\n",c * d)
print("Division:\n",c / d)


Addition:
 [[11 13 15]
 [14 16 18]]
Subtraction:
 [[-9 -9 -9]
 [-6 -6 -6]]
Multiplication:
 [[10 22 36]
 [40 55 72]]
Division:
 [[0.1        0.18181818 0.25      ]
 [0.4        0.45454545 0.5       ]]


In [175]:
# 12. Handling with nul values nan & inf

In [177]:
data1 = np.array([1,2,np.nan,4,np.inf])
print(data1)

[ 1.  2. nan  4. inf]


In [180]:
print(np.isnan(data1))

[False False  True False False]


In [182]:
print(np.isinf(data1))

[False False False False  True]


In [183]:
print(np.nan_to_num(data1))

[1.00000000e+000 2.00000000e+000 0.00000000e+000 4.00000000e+000
 1.79769313e+308]


In [ ]:
# save and load arrays

In [185]:
arr = np.array([1,0,0,8])
print(arr)
np.save("my_arr.npy",arr)

[1 0 0 8]


In [188]:
loaded_arr = np.load("my_arr.npy")
print(loaded_arr)

[1 0 0 8]


In [ ]:
# 1. Create 5x5 matrix with values from 1 to 25
# extract last row, first column, sub matrix containing 3 x 3

In [212]:
matrix = np.array([[1,2,3,4,5],
                  [6,7,8,9,10],
                  [11,12,13,14,15],
                  [16,17,18,19,20],
                  [21,22,23,24,25]])
print(f"Creating 5x5 matrix: \n{matrix}")
print()
print(f"last row:\n {matrix[4]}")
print()
print(f"First column:\n {matrix[:,0]}")
print()

print(f"sub 3 x 3 matrix:\n {matrix[3], [3]}")

Creating 5x5 matrix: 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

last row:
 [21 22 23 24 25]

First column:
 [ 1  6 11 16 21]

sub 3 x 3 matrix:
 (array([16, 17, 18, 19, 20]), [3])


In [51]:
# https://youtu.be/uaTigVkG2dk

In [52]:
# https://youtu.be/uaTigVkG2dk