In [2]:
# import NumPy - convention is. to import as np
import numpy as np

In [3]:
# Python List vs NumPy Array

pythpn_list = [1, 2, 3, 4, 5]

# Numpy Array

numpy_array = np.array([1, 2, 3, 4, 5])

print("Python List: ", pythpn_list)
print("Numpy Array: ", numpy_array)
print("Type of Python List: ", type(pythpn_list))
print("Type of Numpy Array: ", type(numpy_array))

# Key advantages: Vectorized operations (no loops needed)
# Adding 5 to each element in the list and array

pythpn_list_plus_5 = [x + 5 for x in pythpn_list] # requires a loop
numpy_array_plus_5 = numpy_array + 5 # vectorized operation

print("Python List + 5: ", pythpn_list_plus_5)
print("Numpy Array + 5: ", numpy_array_plus_5)


Python List:  [1, 2, 3, 4, 5]
Numpy Array:  [1 2 3 4 5]
Type of Python List:  <class 'list'>
Type of Numpy Array:  <class 'numpy.ndarray'>
Python List + 5:  [6, 7, 8, 9, 10]
Numpy Array + 5:  [ 6  7  8  9 10]


In [4]:
import time

# Large array for performance comparison
large_list = list(range(1000000))
large_array = np.array(large_list)

# Addition operation on Python list
start_time = time.time()
large_list_plus_5 = [x + 5 for x in large_list]
python_time = time.time() - start_time
print("Time taken for Python List addition: {:.2f} seconds".format(python_time))

# Addition operation on NumPy array
start_time = time.time()
large_array_plus_5 = large_array + 5
numpy_time = time.time() - start_time
print("Time taken for NumPy Array addition: {:.2f} seconds".format(numpy_time))
print("Performance improvement: {:.2f} times faster".format(python_time / numpy_time))

Time taken for Python List addition: 0.05 seconds
Time taken for NumPy Array addition: 0.00 seconds
Performance improvement: 11.47 times faster


In [5]:
arr1 = np.array([1,2,3,4,5])
print("Original Array: ", arr1)

Original Array:  [1 2 3 4 5]


In [6]:
# Method 2: Using np.arange() to create an array of numbers from 0 to 9
arr2 = np.arange(10)
print("Array using np.arange(): ", arr2)

Array using np.arange():  [0 1 2 3 4 5 6 7 8 9]


In [7]:
arr3 = np.arange(1, 10, 2)  # Start at 1, end before 10, step by 2
print("Array using np.arange() with start, stop, step: ", arr3)

Array using np.arange() with start, stop, step:  [1 3 5 7 9]


In [8]:
# Method 3: Using np.linspace() to create an array of 5 evenly spaced numbers between 0 and 1
arr4 = np.linspace(0, 1, 5)
print("Array using np.linspace(): ", arr4)

Array using np.linspace():  [0.   0.25 0.5  0.75 1.  ]


In [9]:
# Method 4: Using np.zeros() to create an array of zeros
arr5 = np.zeros(5)
print("Array of zeros: ", arr5)

Array of zeros:  [0. 0. 0. 0. 0.]


In [10]:
# Method 5: Using np.ones() to create an array of ones
arr6 = np.ones(5)
print("Array of ones: ", arr6)


Array of ones:  [1. 1. 1. 1. 1.]


In [11]:
# Method 6: full_like() to create an array filled with a specific value
arr7 = np.full_like(arr1, 7)  # Create an array with the same shape as arr1, filled with 7
print("Array using np.full_like(): ", arr7)

Array using np.full_like():  [7 7 7 7 7]


In [12]:
arr8 = np.full(5,7)
print("Array using np.full(): ", arr8)

Array using np.full():  [7 7 7 7 7]


In [13]:
# Method 7: Identity matrix using np.eye()
arr9 = np.eye(3)  # Create a 3x3 identity matrix
print("Identity Matrix using np.eye():\n", arr9)

Identity Matrix using np.eye():
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
# Method 8: Random numbers using np.random.rand() and np.random.randint()
arr10 = np.random.rand(3,3)  # 3x3 array
print("Random numbers using np.random.rand():\n", arr10)


Random numbers using np.random.rand():
 [[0.7574431  0.65312612 0.18218999]
 [0.49197646 0.06995377 0.74671809]
 [0.94662538 0.94311643 0.4827812 ]]


In [15]:
#Method9: Random integers using np.random.randint()
arr11 = np.random.randint(0, 10, size=(3, 3))
print("Random integers using np.random.randint():\n", arr11)

Random integers using np.random.randint():
 [[7 0 3]
 [8 7 6]
 [0 1 2]]


In [16]:
# Type of the array
print("Type of arr1: ", type(arr1))


Type of arr1:  <class 'numpy.ndarray'>


In [17]:
# Type inference of the array and common data types in NumPy
arr12 = np.array([1, 2, 3])  # Integer array
arr13 = np.array([1.0, 2.0, 3.0])  # Float array
arr14 = np.array([1, 2.0, 3])  # Mixed types, will be upcast to float
arr15 = np.array(['a', 'b', 'c'])  # String array
print("Type of arr12: ", arr12.dtype)
print("Type of arr13: ", arr13.dtype)
print("Type of arr14: ", arr14.dtype)
print("Type of arr15: ", arr15.dtype)


Type of arr12:  int64
Type of arr13:  float64
Type of arr14:  float64
Type of arr15:  <U1


In [18]:
# Specifying data types explicitly
arr16 = np.array([1, 2, 3], dtype=np.float32)
print("Array with specified data type (float32): ", arr16)
arr17 = arr16.astype(np.int32)
print("Array with converted data type (int32): ", arr17)

# Common types and their memory usage int32, int64, float32, float64, bool
print("Memory: int32/float32 = 4 bytes, int64/float64 = 8 bytes = 8 bytes per element")

Array with specified data type (float32):  [1. 2. 3.]
Array with converted data type (int32):  [1 2 3]
Memory: int32/float32 = 4 bytes, int64/float64 = 8 bytes = 8 bytes per element


In [19]:
# Multidimensional arrays and their shapes

# 1 D array
arr18 = np.array([1, 2, 3, 4, 5])
print("1D Array: ", arr18)

1D Array:  [1 2 3 4 5]


In [20]:
# 2D array
arr19 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr19)
print("Shape of 2D Array: ", arr19.shape)
print("Size of 2D Array: ", arr19.size)
print("Number of dimensions of 2D Array: ", arr19.ndim)
print("Data type of 2D Array: ", arr19.dtype)
print("Memory size of each element in 2D Array: ", arr19.itemsize, "bytes")
print("Total memory size of 2D Array: ", arr19.nbytes, "bytes")

2D Array:
 [[1 2 3]
 [4 5 6]]
Shape of 2D Array:  (2, 3)
Size of 2D Array:  6
Number of dimensions of 2D Array:  2
Data type of 2D Array:  int64
Memory size of each element in 2D Array:  8 bytes
Total memory size of 2D Array:  48 bytes


In [21]:
# 3D array
arr20 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D Array:\n", arr20)
print("Shape of 3D Array: ", arr20.shape)
print("Size of 3D Array: ", arr20.size)
print("Number of dimensions of 3D Array: ", arr20.ndim)
print("Data type of 3D Array: ", arr20.dtype)
print("Memory size of each element in 3D Array: ", arr20.itemsize, "bytes")
print("Total memory size of 3D Array: ", arr20.nbytes, "bytes")
print("Total number of elements in 3D Array: ", arr20.size)
print("Total number of dimensions in 3D Array: ", arr20.ndim)
print("Total number of bytes consumed by 3D Array: ", arr20.nbytes)
print("Total number of bytes consumed by each element in 3D Array: ", arr20.itemsize)   
print("Total number of bytes consumed by 3D Array: ", arr20.nbytes)
print("Total number of bytes consumed by each element in 3D Array: ", arr20.itemsize)


3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape of 3D Array:  (2, 2, 2)
Size of 3D Array:  8
Number of dimensions of 3D Array:  3
Data type of 3D Array:  int64
Memory size of each element in 3D Array:  8 bytes
Total memory size of 3D Array:  64 bytes
Total number of elements in 3D Array:  8
Total number of dimensions in 3D Array:  3
Total number of bytes consumed by 3D Array:  64
Total number of bytes consumed by each element in 3D Array:  8
Total number of bytes consumed by 3D Array:  64
Total number of bytes consumed by each element in 3D Array:  8


In [22]:
# Array  Operations: Mathematical Operations

In [23]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
print(f"Array a:{a}")
print(f"Array b:{b}")

# Element wise operation

print("\n*** Element wise operation ***")
print(f"Addition(a + b): {a + b}")
print(f"Subtraction (a - b): {a - b}")
print(f"Multiplication (a * b): {a * b}")
print(f"Division (a / b): {a / b}")
print(f"Power (a ** 2): {a ** 2}")
print(f"Square root: {np.sqrt(a)}")

# Scalar operations (Broadcasting)

print("\n*** Scalar operations (Broadcasting) ***")
print(f"Addition (a + 10): {a + 10}")
print(f"Subtraction (a - 10): {a - 10}")
print(f"Multiplication (a * 10): {a * 10}")
print(f"Division (a / 10): {a / 10}")
print(f"Multiplication (a ** 10): {a ** 10}")

# Comparision Operation

print("\n*** Comparision Operation ***")
print("a > 3???    ",a > 3)
print("Is a == 3?? ", a ==3)
print("Is a <=2 ?? " ,a <= 2)

Array a:[1 2 3 4 5]
Array b:[ 6  7  8  9 10]

*** Element wise operation ***
Addition(a + b): [ 7  9 11 13 15]
Subtraction (a - b): [-5 -5 -5 -5 -5]
Multiplication (a * b): [ 6 14 24 36 50]
Division (a / b): [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
Power (a ** 2): [ 1  4  9 16 25]
Square root: [1.         1.41421356 1.73205081 2.         2.23606798]

*** Scalar operations (Broadcasting) ***
Addition (a + 10): [11 12 13 14 15]
Subtraction (a - 10): [-9 -8 -7 -6 -5]
Multiplication (a * 10): [10 20 30 40 50]
Division (a / 10): [0.1 0.2 0.3 0.4 0.5]
Multiplication (a ** 10): [      1    1024   59049 1048576 9765625]

*** Comparision Operation ***
a > 3???     [False False False  True  True]
Is a == 3??  [False False  True False False]
Is a <=2 ??  [ True  True False False False]


In [24]:
# 8. Aray Manipulation: Reshaping and Resizing

In [25]:
arr = np.arange(10)
print(arr)

# Reshape - Changes view, doesn't copy data
# reshaped = arr.reshape(3,5) # Must match the total size of the provided array (2 * 5 = 10)
reshaped = arr.reshape(2,5)
print("\nReshaped array 2 * 5:")
print(reshaped)

# Flatten - Convert to 1D
flattened =  reshaped.flatten()
print("\nFlattened: ",flattened)

# Reshape with -1 (Auto-calculate dimension)
auto_reshape = arr.reshape(5,-1) # -1 means "Calculate automatically"
print("\nRe shaped:\n",auto_reshape)

# Transpose
matrix  = np.array([[1,2,3,4],[5,6,7,8]])
print("\nOriginal matrix")
print(matrix)
print("\nTransposed")
print(matrix.T)


# Concationation
print("\nConcatenation")
a  = np.array([[1,2,3,4],[5,6,7,8]])
b = np.array([[9,10,11,12],[13,14,15,16]])

print("\nArray a\n",a)
print("\nArray b\n",b)

print("\nVertical concatenation:\n", np.vstack((a,b)))
print("\nHorizontal concatenation:\n", np.hstack((a,b)))

print("\nUsing concatenation\n")
print("\nVertical concatenation using axis = 0:\n")

print(np.concatenate((a,b),axis = 0))
print("\nHorizontal concatenation using axis = 1:\n")
print(np.concatenate((a,b),axis = 1))

[0 1 2 3 4 5 6 7 8 9]

Reshaped array 2 * 5:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Flattened:  [0 1 2 3 4 5 6 7 8 9]

Re shaped:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

Original matrix
[[1 2 3 4]
 [5 6 7 8]]

Transposed
[[1 5]
 [2 6]
 [3 7]
 [4 8]]

Concatenation

Array a
 [[1 2 3 4]
 [5 6 7 8]]

Array b
 [[ 9 10 11 12]
 [13 14 15 16]]

Vertical concatenation:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Horizontal concatenation:
 [[ 1  2  3  4  9 10 11 12]
 [ 5  6  7  8 13 14 15 16]]

Using concatenation


Vertical concatenation using axis = 0:

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Horizontal concatenation using axis = 1:

[[ 1  2  3  4  9 10 11 12]
 [ 5  6  7  8 13 14 15 16]]


# 9. Understanding Dimentions and Axis

# Key concepts:
    # Dimension (ndim): Numpy of axes(1D = 1, 2D = 2, 3D = 3)
    # Axis: The dimension along which an operation is performed (strat at 0)
    # Shape: Size of each dimension (eg: (3,4) = 3 rows , 4 columns)
    # For 2D Arrays: axis=0 = rows(vertical), axis=1 = columns(horizontal)

In [26]:
# Dimensions and Axis

In [27]:
arr1d = np.array([1,2,3,4,5])
print("\n1D  array:")
print(arr1d)
print(f"{arr1d}\nShape: {arr1d.shape}\nndim: {arr1d.ndim}")

print("\n2D  array:")
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)
print(f"{arr2d}\nShape: {arr2d.shape}(rows, column)\nndim: {arr2d.ndim} (axis 0 = rows, axis 1  = columns)")


1D  array:
[1 2 3 4 5]
[1 2 3 4 5]
Shape: (5,)
ndim: 1

2D  array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)(rows, column)
ndim: 2 (axis 0 = rows, axis 1  = columns)


In [28]:
# Axis in operations: specifies which dimension to collapse
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Matrix\n",matrix)
print("Matrix shape:\n",matrix.shape)
# axis = 0: Collapse  rows (operate down columns) -> one value per column

Matrix
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix shape:
 (3, 3)


In [29]:
# Axis = 0 collapse rows (Operate down columns) -> One value per column
sum_axis0 = np.sum(matrix, axis = 0)
print(f"axis 0 sum matrix: \n{sum_axis0}")
print(f"axis 0 shape matrix: \n{sum_axis0.shape}")
print(f"Example. Column 0 sum = {matrix[0,0]} + {matrix[1,0]} + {matrix[2,0]} = {sum_axis0[0]}")
print(f"Example. Column 1 sum = {matrix[0,1]} + {matrix[1,1]} + {matrix[2,1]} = {sum_axis0[1]}")
print(f"Example. Column 2 sum = {matrix[0,2]} + {matrix[1,2]} + {matrix[2,2]} = {sum_axis0[2]}")


sum_axis1 = np.sum(matrix, axis = 1)
print(f"\naxis 1 sum matrix: \n{sum_axis1}")
print(f"\naxis 1 shape matrix:\n{sum_axis1.shape}")
print(f"Example. Row 0 sum = {matrix[0,0]} + {matrix[0,1]} + {matrix[0,2]} = {sum_axis1[0]}")
print(f"Example. Row 1 sum = {matrix[1,0]} + {matrix[1,1]} + {matrix[1,2]} = {sum_axis1[1]}")
print(f"Example. Row 2 sum = {matrix[2,0]} + {matrix[2,1]} + {matrix[2,2]} = {sum_axis1[2]}")


axis 0 sum matrix: 
[12 15 18]
axis 0 shape matrix: 
(3,)
Example. Column 0 sum = 1 + 4 + 7 = 12
Example. Column 1 sum = 2 + 5 + 8 = 15
Example. Column 2 sum = 3 + 6 + 9 = 18

axis 1 sum matrix: 
[ 6 15 24]

axis 1 shape matrix:
(3,)
Example. Row 0 sum = 1 + 2 + 3 = 6
Example. Row 1 sum = 4 + 5 + 6 = 15
Example. Row 2 sum = 7 + 8 + 9 = 24


In [30]:
arr3d = np.array([
     [[1,2,3],   # First 2D slice(page 0)
      [4,5,6]],
     [[7,8,9],   # Second 2D slice (page 1)
      [10,11,12]]])

print("Think: 2 pages, each with 2*3 matrix")
print(f"3D array:\n{arr3d}")
print(f"\n3Dshape:\n{arr3d.shape}")
print()

Think: 2 pages, each with 2*3 matrix
3D array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

3Dshape:
(2, 2, 3)



In [31]:
# Statistical Operations


In [32]:
arrst = np.array([1,2,3,4,5,6,7,8,9])
print("Array", arrst)
print("\n*** Basic  statistics ***")
print(f"Sum: {np.sum(arrst)}")
print(f"Mean: {np.mean(arrst)}")
print(f"Median: {np.median(arrst)}")
print(f"Standard deviation: {np.std(arrst)}")
print(f"Variance: {np.var(arrst)}")
print(f"Min: {np.min(arrst)}")
print(f"Max: {np.max(arrst)}")
print(f"Index of min: {np.argmin(arrst)}")
print(f"Index of max: {np.argmax(arrst)}")



Array [1 2 3 4 5 6 7 8 9]

*** Basic  statistics ***
Sum: 45
Mean: 5.0
Median: 5.0
Standard deviation: 2.581988897471611
Variance: 6.666666666666667
Min: 1
Max: 9
Index of min: 0
Index of max: 8


In [33]:
# 2D array statistics (with axis parameter)
matrix = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("2D array Statistics (with axis parameter")
print("Matrix:", matrix)
print("\n*** 2D statistics ***")
print(f"Sum: {np.sum(matrix)}")
print(f"Sum along rows (axis = 0): {np.sum(matrix, axis = 0)}")
print(f"Sum along columns (axis = 1): {np.sum(matrix, axis =1)}")
print(f"Mean of each column:{np.mean(matrix, axis = 0)}")
print(f"Mean of each row:{np.mean(matrix, axis = 1)}")

2D array Statistics (with axis parameter
Matrix: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

*** 2D statistics ***
Sum: 78
Sum along rows (axis = 0): [15 18 21 24]
Sum along columns (axis = 1): [10 26 42]
Mean of each column:[5. 6. 7. 8.]
Mean of each row:[ 2.5  6.5 10.5]


In [34]:
# 11. Linear Algebra Operation

In [35]:

a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])

print("Matrix a:\n", a)
print("\nMatrix b:\n", b)

print("\nMatrix a + b:\n", a + b)
print("\nMatrix a - b:\n", a - b)
print("\nMatrix a * b:\n", a * b)
print("\nMatrix a / b:\n", a / b)


# Dot products of vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
print(f"Dot product of vectors {v1} and {v2} is: \n{np.dot(v1,v2)}")

#  Matrix properties
matrix =np.array([[1,2],[3,4]])
print("\nMatrix properties")
print(matrix)
print(f"\nDetermenant:\n{np.linalg.det(matrix)}")
print("\nInverse:\n",np.linalg.inv(matrix))
print(f"\nTranspose:\n{matrix.T}")



Matrix a:
 [[1 2 3]
 [4 5 6]]

Matrix b:
 [[ 7  8  9]
 [10 11 12]]

Matrix a + b:
 [[ 8 10 12]
 [14 16 18]]

Matrix a - b:
 [[-6 -6 -6]
 [-6 -6 -6]]

Matrix a * b:
 [[ 7 16 27]
 [40 55 72]]

Matrix a / b:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]
Dot product of vectors [1 2 3 4] and [5 6 7 8] is: 
70

Matrix properties
[[1 2]
 [3 4]]

Determenant:
-2.0000000000000004

Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]

Transpose:
[[1 3]
 [2 4]]


In [36]:
# 12. Array Copying and Views

In [37]:
# Useful array  methods

arr = np.array([9,1,3,6,8,7,2,4,5,3,2,6,8,8])
print(f"Original array:\n{arr}")
# Sorting
print("\nSorting\n")
print(f"Sorting array:\n{np.sort(arr)}")
print(f"Original Unchanged:\n{arr}")
arr.sort()
print("After sort:\n",arr)

print("\nUnique elements\n")
print(np.unique(arr))

print("\nSearching\n")
print("Where is value??: (Index)",np.where(arr > 5))
print("Values where condition is True:", arr[np.where(arr > 5)])

# Stacking Arrays
print("\nStacking")
a = np.array([1,2,3])
b = np.array([4,5,6])

print("Stacking Ex.\n")
print("Array a:",a)
print("Array b:",b)
print("Stack vertically:\n", np.vstack((a,b)))
print("Stack horizontally:\n",np.hstack((a,b)))
print("Stack as column:\n",np.column_stack((a,b)))



Original array:
[9 1 3 6 8 7 2 4 5 3 2 6 8 8]

Sorting

Sorting array:
[1 2 2 3 3 4 5 6 6 7 8 8 8 9]
Original Unchanged:
[9 1 3 6 8 7 2 4 5 3 2 6 8 8]
After sort:
 [1 2 2 3 3 4 5 6 6 7 8 8 8 9]

Unique elements

[1 2 3 4 5 6 7 8 9]

Searching

Where is value??: (Index) (array([ 7,  8,  9, 10, 11, 12, 13]),)
Values where condition is True: [6 6 7 8 8 8 9]

Stacking
Stacking Ex.

Array a: [1 2 3]
Array b: [4 5 6]
Stack vertically:
 [[1 2 3]
 [4 5 6]]
Stack horizontally:
 [1 2 3 4 5 6]
Stack as column:
 [[1 4]
 [2 5]
 [3 6]]


In [38]:
# 13. Practical Ex.Image Processing Simulation


In [50]:
# Simulation a grayscale image as a 2D array with values 0-255
# Let's create a 5x5 grayscale image with random pixel values between 0 and 255
image = np.random.randint(0, 256, size=(5, 5), dtype=np.uint8)
print("Simulated Grayscale Image (5x5):\n", image)

# Image operations: Brightness adjustment (adding a constant value to all pixels)
brightness_adjusted_image = np.clip(image + 50, 0, 255)
print("\nBrightness Adjusted Image (added 50):\n", brightness_adjusted_image)
print("\nOriginal Image:\n", image)
print("\nmean of original image:", np.mean(image))
print("\nmean of brightness adjusted image:", np.mean(brightness_adjusted_image))
print("\nstandard deviation of original image:", np.std(image))
print("\nstandard deviation of brightness adjusted image:", np.std(brightness_adjusted_image))
print("\nminimum value of original image:", np.min(image))
print("\nminimum value of brightness adjusted image:", np.min(brightness_adjusted_image))
print("\nmaximum value of original image:", np.max(image))
print("\nmaximum value of brightness adjusted image:", np.max(brightness_adjusted_image))   

brighter = np.clip(image + 100, 0, 255)
darker = np.clip(image - 100, 0, 255)
print("\nBrighter Image (added 100):\n", brighter)
print("\nBrightness adjusted image mean:", np.mean(brighter))
print("\nDarker Image (subtracted 100):\n", darker)
print("\nDarker image mean:", np.mean(darker))

# contrast adjustment: scaling pixel values
contrast_adjusted_image = np.clip((image - 128) * 1.5 + 128, 0, 255)
print("\nContrast Adjusted Image:\n", contrast_adjusted_image)
print("\nContrast adjusted image mean:", np.mean(contrast_adjusted_image))

# clip meaning: np.clip() is used to limit the values in an array. 
# It takes three arguments: 
    # the input array, 
    # a minimum value, and 
    # a maximum value. 
# Any values in the input array that are less than the minimum value 
    # are set to the minimum value, and 
    # any values greater than the maximum value are set to the maximum value. 
# This is particularly useful in image processing 
    # to ensure that pixel values remain within the valid range (0-255 for 8-bit images).


Simulated Grayscale Image (5x5):
 [[ 67 183 127  82  13]
 [183  34  44 189 151]
 [233 101 156 145 225]
 [ 67  98 166   5 157]
 [ 18  14  25 251 148]]

Brightness Adjusted Image (added 50):
 [[117 233 177 132  63]
 [233  84  94 239 201]
 [ 27 151 206 195  19]
 [117 148 216  55 207]
 [ 68  64  75  45 198]]

Original Image:
 [[ 67 183 127  82  13]
 [183  34  44 189 151]
 [233 101 156 145 225]
 [ 67  98 166   5 157]
 [ 18  14  25 251 148]]

mean of original image: 115.28

mean of brightness adjusted image: 134.56

standard deviation of original image: 73.94999391480705

standard deviation of brightness adjusted image: 70.36822009970126

minimum value of original image: 5

minimum value of brightness adjusted image: 19

maximum value of original image: 251

maximum value of brightness adjusted image: 239

Brighter Image (added 100):
 [[167  27 227 182 113]
 [ 27 134 144  33 251]
 [ 77 201   0 245  69]
 [167 198  10 105   1]
 [118 114 125  95 248]]

Brightness adjusted image mean: 123.12

Da

In [51]:
# simulate the student grades as a 2D array (5 students, 4 subjects)


grades = np.random.randint(0, 101, size=(5, 4), dtype=np.int32)
print("Simulated Student Grades (5 students, 4 subjects):\n", grades)
print("\nMean grades per student:", np.mean(grades, axis=1))
print("Mean grades per subject:", np.mean(grades, axis=0))
print("\nStandard deviation per student:", np.std(grades, axis=1))
print("Standard deviation per subject:", np.std(grades, axis=0))

Simulated Student Grades (5 students, 4 subjects):
 [[65 67 56 66]
 [68 53 12 27]
 [99 72 14  4]
 [88 72 93 52]
 [59 72 16  2]]

Mean grades per student: [63.5  40.   47.25 76.25 37.25]
Mean grades per subject: [75.8 67.2 38.2 30.2]

Standard deviation per student: [ 4.38748219 21.82887995 39.58140346 16.0058583  29.04629925]
Standard deviation per subject: [15.14463601  7.3593478  31.88981028 25.49039035]
