In [1]:
import numpy as np
import time

In [2]:
data = np.random.rand(100000000)

In [3]:
len(data)

100000000

In [4]:
start = time.time()
avg = sum(data) / len(data)
stop = time.time()
print(f"Time taken= {stop - start}")
# Time taken= 7.114558935165405

Time taken= 12.241153001785278


In [5]:
start = time.time()
avg = np.mean(data)
stop = time.time()
print(f"Time taken= {stop - start}")
# Time taken= 0.055589914321899414

Time taken= 0.07678699493408203


# Array
    # An array is continiously arranged dat in a memory. numpy addresses array as the name ndarray which refers to n dimentional array. There are two ways by the arraus can be created in python.
        # Using the array()
        # using the builtin array generative functions

# Create a 0 dimentional array:
    # 0 dimentional arrays are those that do not have any direction and are created using scalar value.


In [6]:
# Creating 0d array

arr0 = np.array(10)
print(arr0)
print(type(arr0))
print(arr0.ndim)
print(arr0.shape) # shape attribute - the number of elements in each dimention as a Tuple i.e here we get the Empty tuple 
print(arr0.size) # Gives the number of elements in array
print(arr0.dtype) # Data type of every element in the array
print(arr0.itemsize)    # space alloted in bytes

10
<class 'numpy.ndarray'>
0
()
1
int64
8


In [7]:
# What is the memory size of integer 32 bit in python?
    # int32 bit

In [8]:
import sys
a = 999999999
print(a)
print(sys.getsizeof(a))   # 28 bit

999999999
28


In [9]:
import sys
a = 9999999999
print(a)
print(sys.getsizeof(a))  # 32 bit

9999999999
32


In [10]:
# Creating 1d array

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.ndim)
print(arr1.shape) # shape attribute - the number of elements in each dimention as a Tuple i.e here we get the Empty tuple 
print(arr1.size) # Gives the number of elements in array
print(arr1.dtype) # Data type of every element in the array
print(arr1.itemsize)    # space alloted in bytes

[1 2 3 4 5]
<class 'numpy.ndarray'>
1
(5,)
5
int64
8


In [11]:
t1 = (3,) # in case of tuple a round bracket with some values and a comma is fundamental
print(type(t1))

<class 'tuple'>


In [12]:
t1 = 3, # in case of tuple a round bracket with some values and a comma is fundamental
print(type(t1))

<class 'tuple'>


In [13]:
# Creating 2d array
arr2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr2)
print(type(arr2))
print(arr2.ndim)
print(arr2.shape) # shape attribute - the number of elements in each dimention as a Tuple i.e here we get the Empty tuple 
print(arr2.size) # Gives the number of elements in array
print(arr2.dtype) # Data type of every element in the array
print(arr2.itemsize)    # space alloted in bytes

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>
2
(2, 5)
10
int64
8


In [14]:
# Creating 3d array
arr3 = np.array([[[1,2,3,4,5,6], [6,7,8,9,10,11]],[[11,22,33,44,55,66],[11,12,13,14,15,16]]])
print(arr3)
print(type(arr3))
print(arr3.ndim)
print(arr3.shape) # shape attribute - the number of elements in each dimention as a Tuple i.e here we get the Empty tuple 
print(arr3.size) # Gives the number of elements in array
print(arr3.dtype) # Data type of every element in the array
print(arr3.itemsize)    # space alloted in bytes

[[[ 1  2  3  4  5  6]
  [ 6  7  8  9 10 11]]

 [[11 22 33 44 55 66]
  [11 12 13 14 15 16]]]
<class 'numpy.ndarray'>
3
(2, 2, 6)
24
int64
8


## Arrays Basic Functions

# reshape() - Reshape Function change the dimention of an array from any shape to any shape with a constrains that the size is shame in teh resultant array


In [19]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr_reshaped2x5 = arr.reshape(2,5)
print(arr_reshaped2x5)
print(type(arr_reshaped2x5))
print(arr_reshaped2x5.shape)
print(arr_reshaped2x5.size)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>
(2, 5)
10


In [25]:
arr_reshaped2x1x5 = arr.reshape(2,1,5)
print(arr_reshaped2x1x5)

[[[ 1  2  3  4  5]]

 [[ 6  7  8  9 10]]]


In [ ]:
# 6:21